# Name of your site (displayed in the header)
name: Sergio J. Miralles

# Short bio or description (displayed in the header)
description: Psicólogo, educador y Ceramísta

google-top: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque imperdiet laoreet turpis, in accumsan ex convallis ut.

# Oferta Web Portada
web: Edició Web
brand: Marca Corporativa
grafics: Grafísmes
music: Gestió Cultural

# Cerámica (Index)
ce-desde: Desde 1972
ce-destacado1: 1r Premio Concurso de Montgat
ce-destacado2: Exposición (1996) 
ce-destacado3: Suburbe (2003)

# Viajes (Index)
vi-descripción: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque imperdiet laoreet turpis, in accumsan ex convallis ut.
vi-text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis euismod mollis tellus nec efficitur. Integer at lacinia dolor. Donec in leo a libero dapibus lacinia eu id leo. Vivamus urna purus, tincidunt ut fermentum eu, condimentum sit amet lectus. Sed consectetur sapien ac tellus ullamcorper egestas. Quisque condimentum nulla luctus.

# K.R.A (Index)
kra-oficial:
kra-yyo:

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/9498876?s=400&u=aee7e89c69bf3dee9903bc85ec6aa33985148325&v=4

phone: 658973617
serveis: Serveis
serveis-lead: Creatius, originals i fets a mà
portfoli: Creacions
portfoli-lead: Treballs destacats

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: sjmiralles@gmail.com
  facebook: 100011066671454
  flickr:
  github:
  behance:
  instagram:
  linkedin:
  pinterest:
  rss: rss
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: 
  googleplus: 

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-157725564-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://sjmiralles.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#


permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-redirect-from # Redirect www
  - jekyll-seo-tag

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# Defaults
defaults:
  -
    scope:
      path: "assets/print"
    values:
      image: true
